# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# PYTHON1.py
# Created on: 2021-12-20 17:17:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Polygons = "Polygons"
Polygons_1 = "Polygons_1"
Polygons_2 = "Polygons_2"
UNION1_shp = "H:\\IGIS\\IGIS SEM 5\\GIS Applications Lab\\toolmaking\\UNION1.shp"

# Process: Union
arcpy.Union_analysis("Polygons #;Polygons_1 #;Polygons_2 #", UNION1_shp, "ALL", "", "GAPS")

